home :
	pdflatex semana_01.tex
	bibtex semana_01.aux
	pdflatex semana_01.tex
	pdflatex semana_01.tex
	make clean
	evince semana_01.pdf &
sp:
	~/../investigacion/tex-live/bin/x86_64-linux/pdflatex semana_01.tex;make clean
clean: 
	rm -f *.out *.log *.toc *.snm *.nav *.aux
